@include('admin.module.partials.quiz-validity-badge')
@include('admin.module.partials.readonly-title')
@include('admin.module.partials.description')
@include('admin.module.partials.quiz-thresholds')
@include('admin.module.partials.status')
